### ISSUE TITLE
Issue with price changes in WooCommerce

### ISSUE THREAD

**Issue by stefanos82** [litespeedtech/lscache_wp#181]
Hello everyone,

I hope you are doing well.

I have an issue which I have already reported to support department via email, but did not receive any reply.

My question is: why don't we have purge option for any form of change in WooCommerce?

Why is stock and status more important than regular price, sale price, sale price dates, and so forth?

Shouldn't anything that resides in product data area which has changed be candidate for purging the cache?

My department is facing a tremendous headache with this behavior, because we are forced to purge the cache with every price change.

**Comment by qtwrk** [comment]
Hi,

If you have checked our [file](https://github.com/litespeedtech/lscache_wp/blob/master/litespeed-cache/thirdparty/lscwp-3rd-woocommerce.cls.php) you will see that change price, set to sale ...etc does purge the cache.

May I know how did you change the product info like price ?  because  we have come across this kind of issue before as if user is using a 3rd party plugin rather than use default WP editor, in that case , it may cause the issue you mentioned.

Best regards,

**Comment by stefanos82** [comment]
I have implemented a custom mechanism that synchronizes our POS data with our website via WooCommerce REST API and without LSCache enabled, all the necessary information gets synced as expected.

As soon as we enable and configure the cache, it does not purge on price change or anything else unless it's stock or status.

**Comment by qtwrk** [comment]
Hi,

If you have custom setup , please consider to integrate LSCWP [purge API](https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:lscwp:purge_api)  that should trigger the purge when information is changed.

Best regards,

**Comment by stefanos82** [comment]
Hey @qtwrk, I haven't used the purge API yet, but so far with the current settings we have managed to configure, we are able to see the necessary changes / updates.

I will close this ticket for now and in case the issue reappears, I will re-open it.

Keep up the good work.

Cheers.
