### ISSUE TITLE
Dev-Upgrade disables Networkwide-plugin

### ISSUE THREAD

**Issue by LarsK1** [litespeedtech/lscache_wp#213]
Hey there,
on upgrading lscache to the latest version, I noticed, that by doing an upgrade, it's being disabled on any page, except the Master one.
Thanks for your help,
Lars

**Comment by LarsK1** [comment]
Is this fixed?

**Comment by hailite** [comment]
Each site can be enabled individually. Will check this later. thanks.

**Comment by J-Rey** [comment]
I'm having the same issue now too

**Comment by J-Rey** [comment]
Okay, I figured it out. If you use the **Toolbox > Beta Test** option on a multisite network then it will no longer keep the plugin activated for the whole network and you'll have to go to **Network Admin > Plugins > Network Activate** for the LiteSpeed plugin to restore things.

Instead of having to deal with that workaround & also to avoid users of individual sites being able to mess with the plugin and affect all the other sites in the network, here are the fixes needed:

- Move the **Beta Test** section to only be available under **Network Admin > Toolbox** (i.e. not under each site)
- Change the functionality of how the upgrade is done so it keeps LSCWP as network activated (or if not possible due to WordPress limitations then at least warn that will need to manually Network Activate afterwards)
- Pop up a warning if detected that is using on a multisite network but LSCWP is not network activated

**Comment by LarsK1** [comment]
Seems to be resolved
